### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dan1664** [FallingLights/Teachable-dl#3] opened 2023-03-26 00:17 UTC
**Describe the bug**
I followed all the steps and all the modules installed in Ubuntu terminal. After I put in the line below, I saw it open up a Chrome browser, go to the website, login, and then it stayed on the main page which shows all the courses available. Then it shut down Chrome and gave me the below Max retries exceeded error.

(env) danny@danny-VirtualBox:~$ python3 main.py --url https://school.patbailouni.com/courses/challenge21311111 --email dan1664@hotmail.com --password *****
Could not download course: https://school.patbailouni.com/courses/challenge21311111 cause: HTTPConnectionPool(host='localhost', port=43325): Max retries exceeded with url: /session/25c596d8858b4817335e16d7adc01f15/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eba86a560>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu via Oracle VM Virtual Box
 - Browser Chrome
 - Version 111

**Comment by HenestrosaConH** [comment] 2023-03-26 18:20
I'm running a similar issue to yours. Here is the log:

(env) PS D:\Projects\Python\Teachable-dll> python main.py --url https://seanallen.teachable.com/courses/681906/lectures/13553588 --email *****@******.*** --password *************
Could not download course: https://seanallen.teachable.com/courses/681906/lectures/13553588 cause: HTTPConnectionPool(host='localhost', port=59559): Max retries exceeded with url: /session/d1e74f4023c647d5e03ee6aeb7014c0f/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000290A1683070>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

- OS: Windows 11
- Browser Chrome
- Version 111

**Comment by FallingLights** [comment] 2023-03-26 19:00
@HenestrosaConH @dan1664 Looks like there are more than 2 layouts for the teachable platform ill write the parser for this new one tomorrow

**Comment by HenestrosaConH** [comment] 2023-03-26 19:12
Looking forward to it. Thank you!

**Comment by dan1664** [comment] 2023-03-26 19:50
@FallingLights amazing, thank you for your time and help!

**Comment by FallingLights** [comment] 2023-03-27 19:12
Test the test branch "new-template-test". Did not get a change to test it myself

**Comment by dan1664** [comment] 2023-03-27 19:52
Just tested it and I got this:

env) danny@danny-VirtualBox:~$ python3 main.py --url https://school.patbailouni.com/courses/challenge21311111 --email dan1664@hotmail.com --password ******
Could not download course: https://school.patbailouni.com/courses/challenge21311111 cause: HTTPConnectionPool(host='localhost', port=56675): Max retries exceeded with url: /session/cbb4c7c8b53e6733e6d32c790a49e7e7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9154b14b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by FallingLights** [comment] 2023-03-27 20:05
@dan1664 If you could, can you send me your email and password to fallingluminosity@protonmail.com so I can test it locally

**Comment by dan1664** [comment] 2023-03-27 20:17
@FallingLights I just sent it via buymeacoffee, thank you for your time and help on this!

**Comment by FallingLights** [comment] 2023-03-27 23:20
@dan1664 Thanks for the coffee! Latest commit on the test branch now works for your site.
@HenestrosaConH also give the try to the latest commit

**Comment by HenestrosaConH** [comment] 2023-03-28 07:09
Here is the new error:

(env) PS D:\Projects\Python\Teachable-dll> python main.py --url https://seanallen.teachable.com/courses/681906  --email ********** --password **********
Could not download course: https://seanallen.teachable.com/courses/681906 cause: 'str' object is not callable

**Comment by FallingLights** [comment] 2023-03-28 09:29
@HenestrosaConH Fixed in the latest commit

**Comment by HenestrosaConH** [comment] 2023-03-28 11:24
Hi again. Now that I've been trying to download another course, I'm running the following error:

(env) PS D:\Projects\Python\Teachable-dll> python main.py --url https://academy.essentialdeveloper.com/courses/enrolled/447455 --email *********** --password ********
Detected new course format
Could not download course: https://academy.essentialdeveloper.com/courses/enrolled/447455 cause: 'charmap' codec can't encode character '\u21b5' in position 422195: character maps to <undefined>

**Comment by FallingLights** [comment] 2023-03-28 12:26
@HenestrosaConH Get latest commit ant run with ``-vv`` argument and send the output if it still throwing the error

**Closed** 2023-03-29 07:55 UTC
Labels: bug

**Comment by HenestrosaConH** [comment] 2023-03-29 08:08
> @HenestrosaConH Mind elaborating on why you have to complete and continue? So far I have not seen the need to do that for the courses that i have downloaded.
> 
> And thanks for coffee!

I tried to download a course that I had not fully completed. When the program tried to download lessons that I had not unlocked, it couldn't find the video because a message appeared saying that I had to complete the previous lesson to unlock the new one.

**Comment by FallingLights** [comment] 2023-03-30 11:17
> > @HenestrosaConH Mind elaborating on why you have to complete and continue? So far I have not seen the need to do that for the courses that i have downloaded.
> > And thanks for coffee!
> 
> I tried to download a course that I had not fully completed. When the program tried to download lessons that I had not unlocked, it couldn't find the video because a message appeared saying that I had to complete the previous lesson to unlock the new one.
> 
> Here is an example of what I'm saying:
> 
> ![image](https://user-images.githubusercontent.com/60482743/228469107-239fade5-1d76-4445-8127-06dc5511301b.png)

Added the option in the commit a94d04d6
